services:
  nginx:
    build: ./nginx
    ports:
      -1337:80
    depends_on:
      - web
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./wayfinder:/app/wayfinder
    ports:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - daphne
  daphne:
    build: ./
    command: daphne --bind 0.0.0.0 -p 8002 app.asgi:application
    ports:
      - 8002:8002
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=wayfinder

volumes:
  postgres_data: