# Generated by Django 5.1.3 on 2024-11-22 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0004_tag_experience_rating_tip_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='title',
        ),
    ]
