# Generated by Django 5.1.3 on 2024-11-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0005_remove_tip_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='tags',
            field=models.ManyToManyField(related_name='experiences', to='wayfinder.tag'),
        ),
    ]
