# Generated by Django 5.1.3 on 2024-11-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0007_alter_location_city_alter_location_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experience_images/'),
        ),
    ]
