# Generated by Django 5.1.3 on 2024-12-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0011_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
